title: 'Top Voice · Cor Modern Tarragona'

author:
  name: 'Rakel Esteve'
  email: 'topvoicetgn@gmail.com'

metadata:
  description: 'Top Voice és un cor modern nascut el 2020 a Tarragona. Fem espectacle, no només concerts.'
  generator: ''
